# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY . .

# Expose the port for FastAPI
EXPOSE 8001

# Run FastAPI when the container launches
CMD ["uvicorn", "scripts.batch_api:app", "--host", "0.0.0.0", "--port", "8001"]